# Generated by Django 4.2.2 on 2023-06-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photopost_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopost',
            name='image3',
        ),
        migrations.AddField(
            model_name='photopost',
            name='image1_lim',
            field=models.BooleanField(default=False, verbose_name='制限1'),
        ),
    ]
