# Generated by Django 4.2.2 on 2023-06-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_remove_photopost_image3_photopost_image1_lim'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopost',
            name='image2_lim',
            field=models.BooleanField(default=False, verbose_name='制限1'),
        ),
    ]
