# Generated by Django 4.2.2 on 2023-06-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photopost_image2_lim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='image1_lim',
            field=models.BooleanField(default=False, verbose_name='ダウンロード許可'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='image2_lim',
            field=models.BooleanField(default=False, verbose_name='ダウンロード許可'),
        ),
    ]
